- name: deploy hadoop HA cluster with zookeeper
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  hosts: [hadoop]

  roles:
       - setup          
       - java
       - zookeeper 
       - hadoop 
      
