- name: deploy hadoop HA cluster with zookeeper
  become: yes
  become_user: root
  become_method: sudo
  hosts: [hadoop]

  roles:          
  #- java
         #  - zookeeper 
       - hadoop 
      
