- name: Bootstrap a host without python2 installed
  become: yes
  raw: apt -y update && apt install -y python

- name: Collect only facts returned by facter
  setup:

- name: Disable IPv6 with sysctl
  sysctl: name={{ item }} value=1 state=present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Reboot
  reboot: 
   test_command: uptime       
