- name: Bootstrap a host without python2 installed
  become: yes
  raw: apt -y update && apt install -y python

- name: Collect only facts returned by facter
  setup:

- name: Disable IPv6
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=""'
    replace: 'GRUB_CMDLINE_LINUX="ipv6.disable=1"'

- name: Disable IPv6
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=(".*)'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT="net.ifnames=0 biosdevname=0 console=ttyS0 ipv6.disable=1"'

- name: Update grub
  shell: update-grub
  become: yes

- name: Reboot
  reboot: 
   test_command: uptime       
