- name: install java
  become: yes
  apt: pkg={{java_package}} state=present update_cache=true

- name: add java path in env 
  become: yes 
  blockinfile:
   path: /etc/profile
   block: |
     export JAVA_HOME= {{ java_home }}
     export PATH=$PATH:$JAVA_HOME/bin
   backup: yes 
